version: "3.9"

services:
  intergration-tests:
    build: ./integration-tests
    depends_on:
      - forum
      - gateway
      - chat
      - auth
      - redis
      - mysql
      - mongodb
  gateway:
    build: ./gateway
    ports: 
      - "8000:3000"
    environment:
      USERS_SERVICE_URL: "http://auth:8088"
      ARTICLES_SERVICE_URL: "http://forum:8080"
      CHAT_SERVICE_URL: "http://chat:8082"
      MONGO_URI: "mongodb://mongodb:27017"
    depends_on:
       - forum
       - auth
       - chat
       - mongodb 
  forum:
    build: ./forum/article
    ports:
      - "8080:8000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017"
      ALLOWED_ORIGINS: "http://frontend:3000"
    depends_on:
      - mongodb
  auth:
    restart: always
    build: ./JWT
    ports:
      - "8088:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=arti2002
      - MYSQL_DATABASE=forum_db
    depends_on:
      - mysql
  chat:
    build: ./realtime-chat
    ports:
      - "8082:8082"
      - "50051:50051"
    environment:
      REDIS_ADDR: "redis:6379"
      AUTH_SERVICE_ADDR: "http://auth:8081"
    depends_on:
      - redis 
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=arti2002
      - MYSQL_DATABASE=forum_db   
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro       
  redis:
    image: redis:latest
    ports:
      - "6379:6379"



  