// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article/:id": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "GetArticleByID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Article"
                ],
                "summary": "GetArticleByID",
                "parameters": [
                    {
                        "description": "Create New Article",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetArticleByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetArticleByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Failed to get article",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerError"
                        }
                    }
                }
            }
        },
        "/articles": {
            "get": {
                "description": "GetAllArticles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Article"
                ],
                "summary": "GetAllArticles",
                "responses": {
                    "201": {
                        "description": "artile",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Article"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Failed to get articles",
                        "schema": {
                            "$ref": "#/definitions/models.InternalServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "CreateNewArticle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Article"
                ],
                "summary": "CreateArticle",
                "parameters": [
                    {
                        "description": "Create New Article",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NewArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Article created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.CreateArticleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Failed to create article",
                        "schema": {
                            "$ref": "#/definitions/models.ServerError"
                        }
                    }
                }
            }
        },
        "/articles/:articleId/comments": {
            "get": {
                "description": "GetCommentsByArticleID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "GetCommentsByArticleID",
                "parameters": [
                    {
                        "description": "Dlete comment",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetCommentsByArticleIDRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Comments",
                        "schema": {
                            "$ref": "#/definitions/models.Comment"
                        }
                    },
                    "500": {
                        "description": "Failed to get comments",
                        "schema": {
                            "$ref": "#/definitions/models.GetCommentsByArticleIDServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "CreateComment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "CreateComment",
                "parameters": [
                    {
                        "description": "Create New Article",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.NewCreateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Comment created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.CreateCommentResponse"
                        }
                    },
                    "400": {
                        "description": "Article ID is required",
                        "schema": {
                            "$ref": "#/definitions/models.CreateCommentBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Failed to create comment",
                        "schema": {
                            "$ref": "#/definitions/models.CreateCommentServerError"
                        }
                    }
                }
            }
        },
        "/articles/:id": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "UpdateArticle\nUpdateArticle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Article"
                ],
                "summary": "UpdateArticle",
                "parameters": [
                    {
                        "description": "Update srticle succesfully",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Article updated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateArticleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Failed to update article",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateServerError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "DeleteArticle\nUpdateArticle",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Article"
                ],
                "summary": "DeleteArticle",
                "parameters": [
                    {
                        "description": "Delete article succesfully",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Article deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteArticleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.StatusForbidden"
                        }
                    },
                    "500": {
                        "description": "Failed to delete article",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteServerError"
                        }
                    }
                }
            }
        },
        "/comments": {
            "get": {
                "description": "GetAllComments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "GetAllComments",
                "responses": {
                    "201": {
                        "description": "200OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetAllCommentsResponse"
                        }
                    },
                    "400": {
                        "description": "Article ID is required",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCommentBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.StatusForbidden"
                        }
                    },
                    "404": {
                        "description": "Comment not found",
                        "schema": {
                            "$ref": "#/definitions/models.StatusCommentNotFound"
                        }
                    },
                    "500": {
                        "description": "Failed to get comments",
                        "schema": {
                            "$ref": "#/definitions/models.GetAllCommentsServerError"
                        }
                    }
                }
            }
        },
        "/comments/:id": {
            "get": {
                "description": "GetCommentById",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "GetCommentById",
                "parameters": [
                    {
                        "description": "Create New Article",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetCommentByIdRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Comment created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.GetCommentByIdResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get comment",
                        "schema": {
                            "$ref": "#/definitions/models.GetCommentByIdServerError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "UpdateComment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "UpdateComment",
                "parameters": [
                    {
                        "description": "Create New Article",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Comment created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCommentResponse"
                        }
                    },
                    "400": {
                        "description": "Article ID is required",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCommentBadRequest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.StatusForbidden"
                        }
                    },
                    "404": {
                        "description": "Comment not found",
                        "schema": {
                            "$ref": "#/definitions/models.StatusCommentNotFound"
                        }
                    },
                    "500": {
                        "description": "Failed to update comment",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateCommentServerError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "DeleteComment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment"
                ],
                "summary": "DeleteComment",
                "parameters": [
                    {
                        "description": "Dlete comment",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.DeleteCommentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Comment delete successfully",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteCommentResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.StatusUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.StatusForbidden"
                        }
                    },
                    "404": {
                        "description": "Comment not found",
                        "schema": {
                            "$ref": "#/definitions/models.StatusCommentNotFound"
                        }
                    },
                    "500": {
                        "description": "Failed to delete comment",
                        "schema": {
                            "$ref": "#/definitions/models.DeleteCommentServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Article": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                },
                "author_id": {
                    "type": "string",
                    "example": "67f64f84963c9e7f74634284"
                },
                "content": {
                    "type": "string",
                    "example": "Content"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                },
                "title": {
                    "type": "string",
                    "example": "New title"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                }
            }
        },
        "models.Comment": {
            "type": "object",
            "properties": {
                "article_id example:": {
                    "type": "string"
                },
                "comment_author": {
                    "type": "string",
                    "example": "6805e865276e7a3ca751f2b1"
                },
                "comment_author_name": {
                    "type": "string",
                    "example": ""
                },
                "comment_id": {
                    "type": "string",
                    "example": "87bcf5bd-9725-4aef-937b-f2e651258c97"
                },
                "comment_text": {
                    "type": "string",
                    "example": "Comment content"
                },
                "created_comment_at": {
                    "type": "string",
                    "example": "2025-04-21T10:44:39.309+00:00"
                },
                "updated_comment_at example:": {
                    "type": "string"
                }
            }
        },
        "models.CreateArticleResponse": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                },
                "author_id": {
                    "type": "string",
                    "example": "67f64f84963c9e7f74634284"
                },
                "content": {
                    "type": "string",
                    "example": "Content"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                },
                "title": {
                    "type": "string",
                    "example": "New title"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                }
            }
        },
        "models.CreateCommentBadRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Article ID is required"
                }
            }
        },
        "models.CreateCommentResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "message": {
                    "type": "string",
                    "example": "Create comment succesfully"
                }
            }
        },
        "models.CreateCommentServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to create comment"
                }
            }
        },
        "models.DeleteArticleRequest": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                }
            }
        },
        "models.DeleteArticleResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "message": {
                    "type": "string",
                    "example": "Delete article succesfully"
                }
            }
        },
        "models.DeleteCommentRequest": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "string",
                    "example": "87bcf5bd-9725-4aef-937b-f2e651258c97"
                }
            }
        },
        "models.DeleteCommentResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "message": {
                    "type": "string",
                    "example": "Comment deleted succesfully"
                }
            }
        },
        "models.DeleteCommentServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to delete comment"
                }
            }
        },
        "models.DeleteServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to delete article"
                }
            }
        },
        "models.GetAllCommentsResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "message": {
                    "type": "string",
                    "example": "Comments list..."
                }
            }
        },
        "models.GetAllCommentsServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to get comments"
                }
            }
        },
        "models.GetArticleByIDRequest": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                }
            }
        },
        "models.GetArticleByIDResponse": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                },
                "author_id": {
                    "type": "string",
                    "example": "67f64f84963c9e7f74634284"
                },
                "content": {
                    "type": "string",
                    "example": "Content"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                },
                "title": {
                    "type": "string",
                    "example": "New title"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                }
            }
        },
        "models.GetCommentByIdRequest": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "type": "string",
                    "example": "87bcf5bd-9725-4aef-937b-f2e651258c97"
                }
            }
        },
        "models.GetCommentByIdResponse": {
            "type": "object",
            "properties": {
                "article_id example:": {
                    "type": "string"
                },
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "comment_author": {
                    "type": "string",
                    "example": "6805e865276e7a3ca751f2b1"
                },
                "comment_author_name": {
                    "type": "string",
                    "example": ""
                },
                "comment_id": {
                    "type": "string",
                    "example": "87bcf5bd-9725-4aef-937b-f2e651258c97"
                },
                "comment_text": {
                    "type": "string",
                    "example": "Comment content"
                },
                "created_comment_at": {
                    "type": "string",
                    "example": "2025-04-21T10:44:39.309+00:00"
                },
                "message": {
                    "type": "string",
                    "example": "Get comment succesfully"
                },
                "updated_comment_at example:": {
                    "type": "string"
                }
            }
        },
        "models.GetCommentByIdServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to get comment"
                }
            }
        },
        "models.GetCommentsByArticleIDRequest": {
            "type": "object",
            "properties": {
                "article_id example:": {
                    "type": "string"
                }
            }
        },
        "models.GetCommentsByArticleIDServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to get comments"
                }
            }
        },
        "models.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request body"
                }
            }
        },
        "models.InternalServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to get article"
                }
            }
        },
        "models.NewArticleRequest": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string",
                    "example": "67f64f84963c9e7f74634284"
                },
                "content": {
                    "type": "string",
                    "example": "Content"
                },
                "title": {
                    "type": "string",
                    "example": "New title"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                }
            }
        },
        "models.NewCreateCommentRequest": {
            "type": "object",
            "properties": {
                "comment_text": {
                    "type": "string",
                    "example": "Comment content"
                }
            }
        },
        "models.ServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to create article"
                }
            }
        },
        "models.StatusCommentNotFound": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "message": {
                    "type": "string",
                    "example": "Comment not founf"
                }
            }
        },
        "models.StatusForbidden": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 403
                },
                "message": {
                    "type": "string",
                    "example": "Forbiden"
                }
            }
        },
        "models.StatusUnauthorized": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 401
                },
                "message": {
                    "type": "string",
                    "example": "Unauthorized"
                }
            }
        },
        "models.UpdateArticleRequest": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                },
                "author_id": {
                    "type": "string",
                    "example": "67f64f84963c9e7f74634284"
                },
                "content": {
                    "type": "string",
                    "example": "Content"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                },
                "title": {
                    "type": "string",
                    "example": "New title"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                }
            }
        },
        "models.UpdateArticleResponse": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "string",
                    "example": "7a2be7e3-b34b-43d6-8e62-daa9f615f037"
                },
                "author_id": {
                    "type": "string",
                    "example": "67f64f84963c9e7f74634284"
                },
                "content": {
                    "type": "string",
                    "example": "Content"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                },
                "title": {
                    "type": "string",
                    "example": "New title"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-04-15T20:27:56.805+00:00"
                }
            }
        },
        "models.UpdateCommentBadRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Article ID is required"
                }
            }
        },
        "models.UpdateCommentRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "comment_author": {
                    "type": "string",
                    "example": "6805e865276e7a3ca751f2b1"
                },
                "comment_id": {
                    "type": "string",
                    "example": "87bcf5bd-9725-4aef-937b-f2e651258c97"
                },
                "comment_text": {
                    "type": "string",
                    "example": "Comment content"
                },
                "created_comment_at": {
                    "type": "string",
                    "example": "2025-04-21T10:44:39.309+00:00"
                },
                "message": {
                    "type": "string",
                    "example": "Get comment succesfully"
                },
                "updated_comment_at example:": {
                    "type": "string"
                }
            }
        },
        "models.UpdateCommentResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 201
                },
                "message": {
                    "type": "string",
                    "example": "Comment updated succesfully"
                }
            }
        },
        "models.UpdateCommentServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to update comment"
                }
            }
        },
        "models.UpdateServerError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "message": {
                    "type": "string",
                    "example": "Failed to update article"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "User service",
	Description:      "AuthServer",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
